### ISSUE TITLE
Error whe access to Jenkins

### ISSUE THREAD

**Issue by ronsonmaria** [geerlingguy/drupal-vm#1441]
### Jenkins Error

 - Bug Report / Support Request

### Your Environment

Vagrant 1.9.5
VirtualBox 5.1.22r115126
-bash: ansible: command not found

### Your OS

 - **macOS** (version)

### Full console output

java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.ComparableTimSort.mergeHi(ComparableTimSort.java:866)
	at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:483)
	at java.util.ComparableTimSort.mergeForceCollapse(ComparableTimSort.java:422)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:222)
	at java.util.Arrays.sort(Arrays.java:1312)
	at java.util.Arrays.sort(Arrays.java:1506)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:141)
	at hudson.ExtensionList.sort(ExtensionList.java:385)
	at hudson.ExtensionList.ensureLoaded(ExtensionList.java:305)
	at hudson.ExtensionList.iterator(ExtensionList.java:157)
	at jenkins.model.Jenkins.getDescriptorByType(Jenkins.java:1519)
	at hudson.plugins.git.GitSCM.onLoaded(GitSCM.java:1732)
Caused: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
Caused: java.lang.Error
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
	at jenkins.model.Jenkins$7.runTask(Jenkins.java:1064)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused: org.jvnet.hudson.reactor.ReactorException
	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:269)
	at jenkins.InitReactorRunner.run(InitReactorRunner.java:47)
	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1088)
	at jenkins.model.Jenkins.<init>(Jenkins.java:904)
	at hudson.model.Hudson.<init>(Hudson.java:85)
	at hudson.model.Hudson.<init>(Hudson.java:81)
	at hudson.WebAppMain$3.run(WebAppMain.java:231)
Caused: hudson.util.HudsonFailedToLoad
	at hudson.WebAppMain$3.run(WebAppMain.java:248)

### Summary

I have installed drupalvm in my new macbook. When I try to access to jenkins I Found this error. I have read that I have to install role java open 1.8:

- { role: geerlingguy.java, java_packages: 'java-1.8.0-openjdk'}

But, this sentence throw an error. 

Someone have the same error?

Thanks.

**Comment by geerlingguy** [comment]
@ronsonmaria - Drupal VM doesn't include Jenkins; you might want to open this issue in another repository corresponding to what you're trying to use (maybe in the java role repo, or the jenkins role repo?).

Closing this out as Drupal VM doesn't offer any official support for running Jenkins alongside other apps.
