### ISSUE TITLE
Drupal vm setup in production failed

### ISSUE THREAD

**Issue by BhagiLimbu** [geerlingguy/drupal-vm#1543]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.1
vboxmanage 5.1.14r112924
ansible 2.2.1.0
```

### Your OS

 - **Linux** (Ubuntu 16.04) DigitalOcean

### Full console output

```
TASK [geerlingguy.drupal : Install Drupal with drush.] *************************
fatal: [139.59.237.185]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/drush", "site-install", "standard", "-y", "--root=/var/www/recruitalytics/web", "--site-name=Recruit-A-Lytics", "--account-name=admin", "--account-pass=admin", "--db-url=mysql://db_raladmin:dbral2017@@localhost/recruitalytics"], "delta": "0:05:15.785284", "end": "2017-09-11 13:49:00.567495", "failed": true, "rc": 1, "start": "2017-09-11 13:43:44.782211", "stderr": "Starting Drupal installation. This takes a while. Consider using the \u001b[1;32;40m\u001b[1m[ok]\u001b[0m\n--notify global option.\nFailed to log error: Warning: PDOStatement::execute(): MySQL server has gone away in Drupal\\Core\\Database\\Statement->execute() (line 59 of /var/www/recruitalytics/web/core/lib/Drupal/Core/Database/Statement.php). #0 /var/www/recruitalytics/web/core/includes/bootstrap.inc(566): _drupal_error_handler_real(2, 'PDOStatement::e...', '/var/www/recrui...', 59, Array)\n#1 [internal function]: _drupal_error_handler(2, 'PDOStatement::e...', '/var/www/recrui...', 59, Array)\n#2 /var/www/recruitalytics/web/core/lib/Drupal/Core/Database/Statement.php(59): PDOStatement->execute(Array)\n#3 /var/www/recruitalytics/web/core/lib/Drupal/Core/Database/Connection.php(624): Drupal\\Core\\Database\\Statement->execute(Array, Array)\n#4 /var/www/recruitalytics/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(87): Drupal\\Core\\Database\\Connection->query('SELECT menu_tre...', Array, Array)\n#5 /var/www/recruitalytics/web/core/lib/Drupal/Core/Database/Query/Select.php(508): Drupal\\Core\\Database\\Driver\\mysql\\Connection->query('SELECT menu_tre...', Array, Array)\n#6 /var/www/recruitalytics/web/core/lib/Drupal/Core/Menu/MenuTreeStorage.php(242): Drupal\\Core\\Database\\Query\\Select->execute()\n#7 /var/www/recruitalytics/web/core/lib/Drupal/Core/Menu/MenuTreeStorage.php(464): Drupal\\Core\\Menu\\MenuTreeStorage->safeExecuteSelect(Object(Drupal\\Core\\Database\\Driver\\mysql\\Select))\n#8 /var/www/recruitalytics/web/core/lib/Drupal/Core/Menu/MenuTreeStorage.php(497): Drupal\\Core\\Menu\\MenuTreeStorage->doFindChildrenRelativeDepth(Array)\n#9 /var/www/recruitalytics/web/core/lib/Drupal/Core/Menu/MenuTreeStorage.php(396): Drupal\\Core\\Menu\\MenuTreeStorage->setParents(Array, Array, Array)\n#10 /var/www/recruitalytics/web/core/lib/Drupal/Core/Menu/MenuTreeStorage.php(300): Drupal\\Core\\Menu\\MenuTreeStorage->preSave(Array, Array)\n#11 /var/www/recruitalytics/web/core/lib/Drupal/Core/Menu/MenuTreeStorage.php(833): Drupal\\Core\\Menu\\MenuTreeStorage->doSave(Array)\n#12 /var/www/recruitalytics/web/core/lib/Drupal/Core/Menu/MenuTreeStorage.php(837): Drupal\\Core\\Menu\\MenuTreeStorage->saveRecursive('entity.comment_...', Array, Array)\n#13 /var/www/recruitalytics/web/core/lib/Drupal/Core/Menu/MenuTreeStorage.php(837): Drupal\\Core\\Menu\\MenuTreeStorage->saveRecursive('system.admin_st...', Array, Array)\n#14 /var/www/recruitalytics/web/core/lib/Drupal/Core/Menu/MenuTreeStorage.php(170): Drupal\\Core\\Menu\\MenuTreeStorage->saveRecursive('system.admin', Array, Array)\n#15 /var/www/recruitalytics/web/core/lib/Drupal/Core/Menu/MenuLinkManager.php(199): Drupal\\Core\\Menu\\MenuTreeStorage->rebuild(Array)\n#16 /var/www/recruitalytics/web/core/lib/Drupal/Core/EventSubscriber/MenuRouterRebuildSubscriber.php(61): Drupal\\Core\\Menu\\MenuLinkManager->rebuild()\n#17 /var/www/recruitalytics/web/core/lib/Drupal/Core/EventSubscriber/MenuRouterRebuildSubscriber.php(49): Drupal\\Core\\EventSubscriber\\MenuRouterRebuildSubscriber->menuLinksRebuild()\n#18 /var/www/recruitalytics/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): Drupal\\Core\\EventSubscriber\\MenuRouterRebuildSubscriber->onRouterRebuild(Object(Symfony\\Component\\EventDispatcher\\Event), 'routing.route_f...', Object(Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))\n#19 /var/www/recruitalytics/web/core/lib/Drupal/Core/Routing/RouteBuilder.php(192): Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher->dispatch('routing.route_f...', Object(Symfony\\Component\\EventDispatcher\\Event))\n#20 /var/www/recruitalytics/web/core/lib/Drupal/Core/ProxyClass/Routing/RouteBuilder.php(83): Drupal\\Core\\Routing\\RouteBuilder->rebuild()\n#21 /var/www/recruitalytics/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php(302): Drupal\\Core\\ProxyClass\\Routing\\RouteBuilder->rebuild()\n#22 /var/www/recruitalytics/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83): Drupal\\Core\\Extension\\ModuleInstaller->install(Array, false)\n#23 /var/www/recruitalytics/web/core/includes/install.core.inc(1800): Drupal\\Core\\ProxyClass\\Extension\\ModuleInstaller->install(Array, false)\n#24 /var/www/recruitalytics/web/core/includes/batch.inc(252): _install_module_batch('page_cache', 'Internal Page C...', Array)\n#25 /var/www/recruitalytics/web/core/includes/form.inc(874): _batch_process()\n#26 /var/www/recruitalytics/web/core/includes/install.core.inc(619): batch_process(Object(Drupal\\Core\\Url), Object(Drupal\\Core\\Url))\n#27 /var/www/recruitalytics/web/core/includes/install.core.inc(540): install_run_task(Array, Array)\n#28 /var/www/recruitalytics/web/core/includes/install.core.inc(117): install_run_tasks(Array)\n#29 /var/www/recruitalytics/vendor/drush/drush/includes/drush.inc(726): install_drupal(Object(Composer\\Autoload\\ClassLoader), Array)\n#30 /var/www/recruitalytics/vendor/drush/drush/includes/drush.inc(711): drush_call_user_func_array('install_drupal', Array)\n#31 /var/www/recruitalytics/vendor/drush/drush/commands/core/drupal/site_install.inc(82): drush_op('install_drupal', Object(Composer\\Autoload\\ClassLoader), Array)\n#32 /var/www/recruitalytics/vendor/drush/drush/commands/core/site_install.drush.inc(255): drush_core_site_install_version('standard', Array)\n#33 /var/www/recruitalytics/vendor/drush/drush/includes/command.inc(422): drush_core_site_install('standard')\n#34 /var/www/recruitalytics/vendor/drush/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)\n#35 /var/www/recruitalytics/vendor/drush/drush/includes/command.inc(199): drush_command('standard')\n#36 /var/www/recruitalytics/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)\n#37 /var/www/recruitalytics/vendor/drush/drush/includes/preflight.inc(66): Drush\\Boot\\BaseBoot->bootstrap_and_dispatch()\n#38 /var/www/recruitalytics/vendor/drush/drush/drush.php(12): drush_main()\n#39 {main}\nFailed to log error: Warning: PDOStatement::execute(): Error reading result set's header in Drupal\\Core\\Database\\Statement->execute() (line 59 of /var/www/recruitalytics/web/core/lib/Drupal/Core/Database/Statement.php). #0 /var/www/recruitalytics/web/core/includes/bootstrap.inc(566): _drupal_error_handler_real(2, 'PDOStatement::e...', '/var/www/recrui...', 59, Array)\n#1 [internal function]: _drupal_error_handler(2, 'PDOStatement::e...', '/var/www/recrui...', 59, Array)\n#2 /var/www/recruitalytics/web/core/lib/Drupal/Core/Database/Statement.php(59): PDOStatement->execute(Array)\n#3 /var/www/recruitalytics/web/core/lib/Drupal/Core/Database/Connection.php(624): Drupal\\Core\\Database\\Statement->execute(Array, Array)\n#4 /var/www/recruitalytics/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(87): Drupal\\Core\\Database\\Connection->query('SELECT menu_tre...', Array, Array)\n#5 /var/www/recruitalytics/web/core/lib/Drupal/Core/Database/Query/Select.php(508): Drupal\\Core\\Database\\Driver\\mysql\\Connection->query('SELECT menu_tre...', Array, Array)\n#6 /var/www/recruitalytics/web/core/lib/Drupal/Core/Menu/MenuTreeStorage.php(242): Drupal\\Core\\Database\\Query\\Select->execute()\n#7 /var/www/recruitalytics/web/core/lib/Drupal/Core/Menu/MenuTreeStorage.php(464): Drupal\\Core\\Menu\\MenuTreeStorage->safeExecuteSelect(Object(Drupal\\Core\\Database\\Driver\\mysql\\Select))\n#8 /var/www/recruitalytics/web/core/lib/Drupal/Core/Menu/MenuTreeStorage.php(497): Drupal\\Core\\Menu\\MenuTreeStorage->doFindChildrenRelativeDepth(Array)\n#9 /var/www/recruitalytics/web/core/lib/Drupal/Core/Menu/MenuTreeStorage.php(396): Drupal\\Core\\Menu\\MenuTreeStorage->setParents(Array, Array, Array)\n#10 /var/www/recruitalytics/web/core/lib/Drupal/Core/Menu/MenuTreeStorage.php(300): Drupal\\Core\\Menu\\MenuTreeStorage->preSave(Array, Array)\n#11 /var/www/recruitalytics/web/core/lib/Drupal/Core/Menu/MenuTreeStorage.php(833): Drupal\\Core\\Menu\\MenuTreeStorage->doSave(Array)\n#12 /var/www/recruitalytics/web/core/lib/Drupal/Core/Menu/MenuTreeStorage.php(837): Drupal\\Core\\Menu\\MenuTreeStorage->saveRecursive('entity.comment_...', Array, Array)\n#13 /var/www/recruitalytics/web/core/lib/Drupal/Core/Menu/MenuTreeStorage.php(837): Drupal\\Core\\Menu\\MenuTreeStorage->saveRecursive('system.admin_st...', Array, Array)\n#14 /var/www/recruitalytics/web/core/lib/Drupal/Core/Menu/MenuTreeStorage.php(170): Drupal\\Core\\Menu\\MenuTreeStorage->saveRecursive('system.admin', Array, Array)\n#15 /var/www/recruitalytics/web/core/lib/Drupal/Core/Menu/MenuLinkManager.php(199): Drupal\\Core\\Menu\\MenuTreeStorage->rebuild(Array)\n#16 /var/www/recruitalytics/web/core/lib/Drupal/Core/EventSubscriber/MenuRouterRebuildSubscriber.php(61): Drupal\\Core\\Menu\\MenuLinkManager->rebuild()\n#17 /var/www/recruitalytics/web/core/lib/Drupal/Core/EventSubscriber/MenuRouterRebuildSubscriber.php(49): Drupal\\Core\\EventSubscriber\\MenuRouterRebuildSubscriber->menuLinksRebuild()\n#18 /var/www/recruitalytics/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): Drupal\\Core\\EventSubscriber\\MenuRouterRebuildSubscriber->onRouterRebuild(Object(Symfony\\Component\\EventDispatcher\\Event), 'routing.route_f...', Object(Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))\n#19 /var/www/recruitalytics/web/core/lib/Drupal/Core/Routing/RouteBuilder.php(192): Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher->dispatch('routing.route_f...', Object(Symfony\\Component\\EventDispatcher\\Event))\n#20 /var/www/recruitalytics/web/core/lib/Drupal/Core/ProxyClass/Routing/RouteBuilder.php(83): Drupal\\Core\\Routing\\RouteBuilder->rebuild()\n#21 /var/www/recruitalytics/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php(302): Drupal\\Core\\ProxyClass\\Routing\\RouteBuilder->rebuild()\n#22 /var/www/recruitalytics/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83): Drupal\\Core\\Extension\\ModuleInstaller->install(Array, false)\n#23 /var/www/recruitalytics/web/core/includes/install.core.inc(1800): Drupal\\Core\\ProxyClass\\Extension\\ModuleInstaller->install(Array, false)\n#24 /var/www/recruitalytics/web/core/includes/batch.inc(252): _install_module_batch('page_cache', 'Internal Page C...', Array)\n#25 /var/www/recruitalytics/web/core/includes/form.inc(874): _batch_process()\n#26 /var/www/recruitalytics/web/core/includes/install.core.inc(619): batch_process(Object(Drupal\\Core\\Url), Object(Drupal\\Core\\Url))\n#27 /var/www/recruitalytics/web/core/includes/install.core.inc(540): install_run_task(Array, Array)\n#28 /var/www/recruitalytics/web/core/includes/install.core.inc(117): install_run_tasks(Array)\n#29 /var/www/recruitalytics/vendor/drush/drush/includes/drush.inc(726): install_drupal(Object(Composer\\Autoload\\ClassLoader), Array)\n#30 /var/www/recruitalytics/vendor/drush/drush/includes/drush.inc(711): drush_call_user_func_array('install_drupal', Array)\n#31 /var/www/recruitalytics/vendor/drush/drush/commands/core/drupal/site_install.inc(82): drush_op('install_drupal', Object(Composer\\Autoload\\ClassLoader), Array)\n#32 /var/www/recruitalytics/vendor/drush/drush/commands/core/site_install.drush.inc(255): drush_core_site_install_version('standard', Array)\n#33 /var/www/recruitalytics/vendor/drush/drush/includes/command.inc(422): drush_core_site_install('standard')\n#34 /var/www/recruitalytics/vendor/drush/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)\n#35 /var/www/recruitalytics/vendor/drush/drush/includes/command.inc(199): drush_command('standard')\n#36 /var/www/recruitalytics/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)\n#37 /var/www/recruitalytics/vendor/drush/drush/includes/preflight.inc(66): Drush\\Boot\\BaseBoot->bootstrap_and_dispatch()\n#38 /var/www/recruitalytics/vendor/drush/drush/drush.php(12): drush_main()\n#39 {main}\nPDOException: SQLSTATE[HY000] [2002] No such file or directory in    \u001b[31;40m\u001b[1m[error]\u001b[0m\n/var/www/recruitalytics/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php:149\nStack trace:\n#0\n/var/www/recruitalytics/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(149):\nPDO->__construct('mysql:host=loca...', 'db_raladmin', 'dbral2017@',\nArray)\n#1\n/var/www/recruitalytics/web/core/lib/Drupal/Core/Database/Database.php(376):\nDrupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)\n#2\n/var/www/recruitalytics/web/core/lib/Drupal/Core/Database/Database.php(166):\nDrupal\\Core\\Database\\Database::openConnection('default',\n'dedicated_dblog')\n#3\n/var/www/recruitalytics/web/core/modules/dblog/src/Logger/DbLog.php(102):\nDrupal\\Core\\Database\\Database::getConnection('dedicated_dblog',\n'default')\n#4\n/var/www/recruitalytics/web/core/lib/Drupal/Core/Logger/LoggerChannel.php(136):\nDrupal\\dblog\\Logger\\DbLog->log(3, '%type: @message...', Array)\n#5 /var/www/recruitalytics/web/core/includes/bootstrap.inc(406):\nDrupal\\Core\\Logger\\LoggerChannel->log(3, '%type: @message...', Array)\n#6\n/var/www/recruitalytics/web/core/lib/Drupal/Core/EventSubscriber/MenuRouterRebuildSubscriber.php(67):\nwatchdog_exception('menu',\nObject(Drupal\\Component\\Plugin\\Exception\\PluginException))\n#7\n/var/www/recruitalytics/web/core/lib/Drupal/Core/EventSubscriber/MenuRouterRebuildSubscriber.php(49):\nDrupal\\Core\\EventSubscriber\\MenuRouterRebuildSubscriber->menuLinksRebuild()\n#8\n/var/www/recruitalytics/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111):\nDrupal\\Core\\EventSubscriber\\MenuRouterRebuildSubscriber->onRouterRebuild(Object(Symfony\\Component\\EventDispatcher\\Event),\n'routing.route_f...',\nObject(Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))\n#9\n/var/www/recruitalytics/web/core/lib/Drupal/Core/Routing/RouteBuilder.php(192):\nDrupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher->dispatch('routing.route_f...',\nObject(Symfony\\Component\\EventDispatcher\\Event))\n#10\n/var/www/recruitalytics/web/core/lib/Drupal/Core/ProxyClass/Routing/RouteBuilder.php(83):\nDrupal\\Core\\Routing\\RouteBuilder->rebuild()\n#11\n/var/www/recruitalytics/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php(302):\nDrupal\\Core\\ProxyClass\\Routing\\RouteBuilder->rebuild()\n#12\n/var/www/recruitalytics/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83):\nDrupal\\Core\\Extension\\ModuleInstaller->install(Array, false)\n#13 /var/www/recruitalytics/web/core/includes/install.core.inc(1800):\nDrupal\\Core\\ProxyClass\\Extension\\ModuleInstaller->install(Array,\nfalse)\n#14 /var/www/recruitalytics/web/core/includes/batch.inc(252):\n_install_module_batch('page_cache', 'Internal Page C...', Array)\n#15 /var/www/recruitalytics/web/core/includes/form.inc(874):\n_batch_process()\n#16 /var/www/recruitalytics/web/core/includes/install.core.inc(619):\nbatch_process(Object(Drupal\\Core\\Url), Object(Drupal\\Core\\Url))\n#17 /var/www/recruitalytics/web/core/includes/install.core.inc(540):\ninstall_run_task(Array, Array)\n#18 /var/www/recruitalytics/web/core/includes/install.core.inc(117):\ninstall_run_tasks(Array)\n#19\n/var/www/recruitalytics/vendor/drush/drush/includes/drush.inc(726):\ninstall_drupal(Object(Composer\\Autoload\\ClassLoader), Array)\n#20\n/var/www/recruitalytics/vendor/drush/drush/includes/drush.inc(711):\ndrush_call_user_func_array('install_drupal', Array)\n#21\n/var/www/recruitalytics/vendor/drush/drush/commands/core/drupal/site_install.inc(82):\ndrush_op('install_drupal', Object(Composer\\Autoload\\ClassLoader),\nArray)\n#22\n/var/www/recruitalytics/vendor/drush/drush/commands/core/site_install.drush.inc(255):\ndrush_core_site_install_version('standard', Array)\n#23\n/var/www/recruitalytics/vendor/drush/drush/includes/command.inc(422):\ndrush_core_site_install('standard')\n#24\n/var/www/recruitalytics/vendor/drush/drush/includes/command.inc(231):\n_drush_invoke_hooks(Array, Array)\n#25\n/var/www/recruitalytics/vendor/drush/drush/includes/command.inc(199):\ndrush_command('standard')\n#26\n/var/www/recruitalytics/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67):\ndrush_dispatch(Array)\n#27\n/var/www/recruitalytics/vendor/drush/drush/includes/preflight.inc(66):\nDrush\\Boot\\BaseBoot->bootstrap_and_dispatch()\n#28 /var/www/recruitalytics/vendor/drush/drush/drush.php(12):\ndrush_main()\n#29 {main}\nPDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away in /var/www/recruitalytics/web/core/lib/Drupal/Core/Database/Statement.php:59\nStack trace:\n#0 /var/www/recruitalytics/web/core/lib/Drupal/Core/Database/Statement.php(59): PDOStatement->execute(Array)\n#1 /var/www/recruitalytics/web/core/lib/Drupal/Core/Database/Connection.php(624): Drupal\\Core\\Database\\Statement->execute(Array, Array)\n#2 /var/www/recruitalytics/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(87): Drupal\\Core\\Database\\Connection->query('DELETE FROM {se...', Array, Array)\n#3 /var/www/recruitalytics/web/core/lib/Drupal/Core/Database/Query/Delete.php(55): Drupal\\Core\\Database\\Driver\\mysql\\Connection->query('DELETE FROM {se...', Array, Array)\n#4 /var/www/recruitalytics/web/core/lib/Drupal/Core/Lock/DatabaseLockBackend.php(163): Drupal\\Core\\Database\\Query\\Delete->execute()\n#5 /var/www/recruitalytics/web/core/includes/bootstrap.inc(1025): Drupal\\Core\\Lock\\DatabaseLockBackend->releaseAll()\n#6 [internal function]: _drupal_shutdown_function()\n#7 {main}\n\nNext Drupal\\Core\\Database\\DatabaseExceptionWrapper: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away: DELETE FROM {semaphore} \nWHERE value = :db_condition_placeholder_0; Array\n(\n    [:db_condition_placeholder_0] => 131783663159b694383a81b4.25096451\n)\n in /var/www/recruitalytics/web/core/lib/Drupal/Core/Database/Connection.php:685\nStack trace:\n#0 /var/www/recruitalytics/web/core/lib/Drupal/Core/Database/Connection.php(649): Drupal\\Core\\Database\\Connection->handleQueryException(Object(PDOException), 'DELETE FROM {se...', Array, Array)\n#1 /var/www/recruitalytics/web/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(87): Drupal\\Core\\Database\\Connection->query('DELETE FROM {se...', Array, Array)\n#2 /var/www/recruitalytics/web/core/lib/Drupal/Core/Database/Query/Delete.php(55): Drupal\\Core\\Database\\Driver\\mysql\\Connection->query('DELETE FROM {se...', Array, Array)\n#3 /var/www/recruitalytics/web/core/lib/Drupal/Core/Lock/DatabaseLockBackend.php(163): Drupal\\Core\\Database\\Query\\Delete->execute()\n#4 /var/www/recruitalytics/web/core/includes/bootstrap.inc(1025): Drupal\\Core\\Lock\\DatabaseLockBackend->releaseAll()\n#5 [internal function]: _drupal_shutdown_function()\n#6 {main}", "stdout": "You are about to DROP all tables in your 'recruitalytics' database. Do you want to continue? (y/n): y\n<h1>Uncaught exception thrown in shutdown function.</h1><p><em class=\"placeholder\">Drupal\\Core\\Database\\DatabaseExceptionWrapper</em>: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away: DELETE FROM {semaphore} \nWHERE value = :db_condition_placeholder_0; Array\n(\n    [:db_condition_placeholder_0] =&gt; 131783663159b694383a81b4.25096451\n)\n in <em class=\"placeholder\">_drupal_shutdown_function()</em> (line <em class=\"placeholder\">1025</em> of <em class=\"placeholder\">/var/www/recruitalytics/web/core/includes/bootstrap.inc</em>). <pre class=\"backtrace\">_drupal_shutdown_function()\n</pre></p><hr />", "stdout_lines": ["You are about to DROP all tables in your 'recruitalytics' database. Do you want to continue? (y/n): y", "<h1>Uncaught exception thrown in shutdown function.</h1><p><em class=\"placeholder\">Drupal\\Core\\Database\\DatabaseExceptionWrapper</em>: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away: DELETE FROM {semaphore} ", "WHERE value = :db_condition_placeholder_0; Array", "(", "    [:db_condition_placeholder_0] =&gt; 131783663159b694383a81b4.25096451", ")", " in <em class=\"placeholder\">_drupal_shutdown_function()</em> (line <em class=\"placeholder\">1025</em> of <em class=\"placeholder\">/var/www/recruitalytics/web/core/includes/bootstrap.inc</em>). <pre class=\"backtrace\">_drupal_shutdown_function()", "</pre></p><hr />"], "warnings": []}
```

### Summary

I follow production setup instruction as mentioned here - http://docs.drupalvm.com/en/latest/other/production/ and run command : DRUPALVM_ENV=prod ansible-playbook -i prod/inventory provisioning/playbook.yml --become --ask-become-pass on Drupal-vm directory, few minutes later it stop at Install Drupal with drush and throw exception. When I type url on browser http://domain.com/ it redirects to Ubuntu apache page instead of install.php. Appreciate if you could share your experience.

Thank you.
Bhagi

**Comment by geerlingguy** [comment]
It looks like drush is failing the database import step, with 'MySQL has gone away'. Do you know what kind of server you have running in production? It should be at least a 1 GB RAM instance, if not 2 or more, otherwise things like MySQL just dying and restarting will happen fairly regularly.

Also, it could just need a restart—try restarting the server, then running the provisioning command again, and see if it works the second time.

**Comment by BhagiLimbu** [comment]
Thanks for quick response, after upgrade CPU 1GB its successfully deployed on server. However, varnish port number  is not set up correctly, its point to default port : 6081 instead of port 80. After, I change manually port number and reload and restart varnish (https://stackoverflow.com/questions/30616715/how-to-set-varnish-to-run-on-port-80-malfunction-of-daemon-opts-set-in-etc-def). It works correctly. I wonder if this part is missing on deployment script set up port 80 on /etc/default/varnish.

Note- My repository is in bitbucket private mode and without setup server ssh key manually on bitbucket it didn't allow download repository from bitbucket.  Hope, it can help someone.

**Comment by oxyc** [comment]
So you got it working? Can I close this. The default configurations have varnish to listen on port 81. You can change it by setting:

```yaml
varnish_listen_port: "80"
varnish_default_backend_port: "81"
apache_listen_port: "81"
```

http://docs.drupalvm.com/en/latest/extras/varnish/

**Comment by BhagiLimbu** [comment]
Please close this issue. Thank you
