### ISSUE TITLE
Getting 'no implicit conversion of nil into String' from hostsupdater

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#2112]
### Issue Type

 - Bug Report

### Your OS

 - **macOS**

### Full console output

```
$ vagrant up         
Bringing machine 'drupalvm' up with 'virtualbox' provider...
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
Traceback (most recent call last):
	32: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
	31: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:201:in `action'
	30: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:201:in `call'
	29: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/environment.rb:613:in `lock'
	28: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:215:in `block in action'
	27: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:246:in `action_raw'
	26: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `run'
	25: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/util/busy.rb:19:in `busy'
	24: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `block in run'
	23: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builder.rb:149:in `call'
	22: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	21: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
	20: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	19: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builtin/call.rb:43:in `call'
	18: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `run'
	17: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/util/busy.rb:19:in `busy'
	16: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `block in run'
	15: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builder.rb:149:in `call'
	14: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	13: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/providers/virtualbox/action/created.rb:15:in `call'
	12: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	11: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/commands/up/middleware/store_box_metadata.rb:33:in `call'
	10: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	 9: from /Users/jgeerling/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.1.1.160/lib/vagrant-hostsupdater/Action/UpdateHosts.rb:17:in `call'
	 8: from /Users/jgeerling/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.1.1.160/lib/vagrant-hostsupdater/HostsUpdater.rb:35:in `addHostEntries'
	 7: from /Users/jgeerling/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.1.1.160/lib/vagrant-hostsupdater/HostsUpdater.rb:35:in `each'
	 6: from /Users/jgeerling/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.1.1.160/lib/vagrant-hostsupdater/HostsUpdater.rb:36:in `block in addHostEntries'
	 5: from /Users/jgeerling/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.1.1.160/lib/vagrant-hostsupdater/HostsUpdater.rb:36:in `each'
	 4: from /Users/jgeerling/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.1.1.160/lib/vagrant-hostsupdater/HostsUpdater.rb:42:in `block (2 levels) in addHostEntries'
	 3: from /Users/jgeerling/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.1.1.160/lib/vagrant-hostsupdater/HostsUpdater.rb:73:in `createHostEntry'
	 2: from /Users/jgeerling/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.1.1.160/lib/vagrant-hostsupdater/HostsUpdater.rb:126:in `signature'
	 1: from /Users/jgeerling/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.1.1.160/lib/vagrant-hostsupdater/HostsUpdater.rb:126:in `hexdigest'
/Users/jgeerling/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.1.1.160/lib/vagrant-hostsupdater/HostsUpdater.rb:126:in `digest': no implicit conversion of nil into String (TypeError)
```

### Summary

After upgrading to Vagrant 2.2.14 (was on 2.2.10), I am getting this error from hostsupdater. I did a full `expunge` and reinstall, and it makes no difference.

I even printed out `aliases` as they are passed to `hostsupdater`, and that list in my case is:

```
["www.drupalvm.test", "adminer.drupalvm.test", "xhprof.drupalvm.test", "pimpmylog.drupalvm.test", "dashboard.drupalvm.test"]
```

**Comment by geerlingguy** [comment]
Seems related: https://github.com/agiledivider/vagrant-hostsupdater/issues/102

Not sure why this is happening now, though.

**Comment by geerlingguy** [comment]
Current workaround:

```
vagrant plugin expunge
vagrant plugin install vagrant-hostmanager
```

**Comment by geerlingguy** [comment]
Not sure where it comes from, but I'm going to move on for now and see if anyone else experiences the same issue.

**Comment by vaccinemedia** [comment]
Duplicate of #2110 which I closed this morning. I managed to fix the issue by uninstalling the latest version of vagrant and installing 2.2.0 and this fixed the issue so I think it's an issue with vagrant and not drupal-vm

**Comment by jplana-ubc** [comment]
After updating from MacOs Catalina to Big Sur, and Virtualbox and Vagrant I started receiving this error on provisioning.

The workaround of reinstalling vagrant-hostsupdater fixed the issue for me. Thank you.

**Comment by geerlingguy** [comment]
Thanks for the feedback; it's definitely not a drupal-vm issue, but since there are likely a substantial number of users it may affect, I want to document the issue here and see if we can find a better workaround :)

**Comment by akarazeev** [comment]
Hi @geerlingguy! I got the same error this morning. As a workaround I added implicit conversion to string of `uuid` ->` uuid.to_s` (`~/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.1.1.160/lib/vagrant-hostsupdater/HostsUpdater.rb:126`) and it worked

**Comment by geerlingguy** [comment]
@akarazeev - Great! I just posted https://github.com/agiledivider/vagrant-hostsupdater/pull/188 and we'll see if that could get merged and released. It seems like maybe this happens, though, when the plugin is not getting a UUID from Vagrant—it looks like Vagrant itself could be looping through plugins before the VM is ready for the plugins to act on it :/

**Comment by cgsmith** [comment]
@akarazeev are you able to test the new release before I push it to RubyGems

**Comment by akarazeev** [comment]
@cgsmith @geerlingguy Thank you guys for quick reaction, the issue has gone after this hot fix ;) Have a nice day!

**Comment by geerlingguy** [comment]
@cgsmith - Can you hold a moment before releasing—I'm testing locally as well...

**Comment by cgsmith** [comment]
@geerlingguy yes of course.

**Comment by geerlingguy** [comment]
@cgsmith - Looks like it fixed the problem for me as well! It looks like the root problem may be that Vagrant is calling out to the plugin _seven_ times now :D

```
$ vagrant up
Bringing machine 'drupalvm' up with 'virtualbox' provider...
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater] Writing the following entries to (/etc/hosts)
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  drupalvm.test  # VAGRANT: d41d8cd98f00b204e9800998ecf8427e (drupalvm) / 
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  www.drupalvm.test  # VAGRANT: d41d8cd98f00b204e9800998ecf8427e (drupalvm) / 
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  adminer.drupalvm.test  # VAGRANT: d41d8cd98f00b204e9800998ecf8427e (drupalvm) / 
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  xhprof.drupalvm.test  # VAGRANT: d41d8cd98f00b204e9800998ecf8427e (drupalvm) / 
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  pimpmylog.drupalvm.test  # VAGRANT: d41d8cd98f00b204e9800998ecf8427e (drupalvm) / 
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  dashboard.drupalvm.test  # VAGRANT: d41d8cd98f00b204e9800998ecf8427e (drupalvm) / 
==> drupalvm: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file.
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
==> drupalvm: Cloning VM...
==> drupalvm: Matching MAC address for NAT networking...
==> drupalvm: Checking if box 'geerlingguy/drupal-vm' version '2.0.10' is up to date...
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
==> drupalvm: Setting the name of the VM: drupalvm.test
==> drupalvm: Clearing any previously set network interfaces...
==> drupalvm: Preparing network interfaces based on configuration...
    drupalvm: Adapter 1: nat
    drupalvm: Adapter 2: hostonly
==> drupalvm: Forwarding ports...
    drupalvm: 22 (guest) => 2222 (host) (adapter 1)
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
==> drupalvm: Running 'pre-boot' VM customizations...
==> drupalvm: Booting VM...
==> drupalvm: Waiting for machine to boot. This may take a few minutes...
    drupalvm: SSH address: 127.0.0.1:2222
    drupalvm: SSH username: vagrant
    drupalvm: SSH auth method: private key
==> drupalvm: Machine booted and ready!
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
```

Anyways... the fix does work and makes it so the plugin doesn't prevent me from starting machines.

**Comment by cgsmith** [comment]
Ooof... I'll put the update out to ruby gems. hopefully vagrant can address the plugin issue.

**Comment by geerlingguy** [comment]
lol, and if I restart the VM, it calls hostsupdater _12 more times_ (same output each time).

**Comment by geerlingguy** [comment]
Closing this out, as the main problem has been fixed by the hostsupdater update. The multiple-times-output is annoying, but that seems like it may be an unrelated Vagrant bug.

**Comment by oxyc** [comment]
> Closing this out, as the main problem has been fixed by the hostsupdater update. The multiple-times-output is annoying, but that seems like it may be an unrelated Vagrant bug.

I see the same with vagrant-hostmanager as well

**Comment by jonaslejon** [comment]
Same problem here. On macOS Big Sur

**Comment by geerlingguy** [comment]
@jonaslejon - Can you try the following:

```
$ vagrant plugin uninstall vagrant-hostsmanager
$ vagrant plugin install vagrant-hostsmanager
```

**Comment by geerlingguy** [comment]
@oxyc - This seems to be a new bug in Vagrant... do you think I should go open a bug in the tracker?

**Comment by oxyc** [comment]
Seems it was labeled works as intended: https://github.com/hashicorp/vagrant/issues/12070#issuecomment-732271918

Also https://github.com/hashicorp/vagrant/issues/12034 https://github.com/agiledivider/vagrant-hostsupdater/issues/187

**Comment by geerlingguy** [comment]
Odd :(

**Comment by lieb77** [comment]
$ vagrant plugin uninstall vagrant-hostsmanager
$ vagrant plugin install vagrant-hostsmanager

Upgraded vagrant-hostmanager to v1.2.0 which seems to have fixed the problem. Thanks.

**Comment by jonaslejon** [comment]
@geerlingguy 

```
➜  ~ vagrant plugin install vagrant-hostsmanager
Installing the 'vagrant-hostsmanager' plugin. This can take a few minutes...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

Unable to resolve dependency: user requested 'vagrant-hostsmanager (> 0)'
```

**Comment by geerlingguy** [comment]
@jonaslejon - It's `vagrant-hostmanager` (note the singular).

**Comment by zerogravity86** [comment]
> 
> 
> Thanks for the feedback; it's definitely not a drupal-vm issue, but since there are likely a substantial number of users it may affect, I want to document the issue here and see if we can find a better workaround :)

@geerlingguy, I experience the same issue on Windows 10 with Virtualbox 6.1.16, Vagrant 2.2.14. I could do a vagrant upwith hostmanager instead, hostsupdater uninstalled. But the vagrant up kept hanging at running ansible playbook. The dashboard was ready, but Drupal has not got installed. 

In a new git bash window, every vagrant command lead to the installation of hostsupdater.

**Comment by yuginaili** [comment]
$ vagrant plugin uninstall vagrant-hostsmanager
$ vagrant plugin install vagrant-hostsmanager

Confirming this fixed the issue on macOS Big Sur with VirtualBox 6.1.16 and Vagrant 2.2.14

**Comment by khurram-wasim** [comment]
I was getting this issue on Vagrant 2.2.14
I uninstalled 2.2.14 and installed Vagrant 2.2.13 from [here](https://releases.hashicorp.com/vagrant/2.2.13/), and it worked fine
