### ISSUE TITLE
The following SSH command responded with a non-zero exit status. Vagrant assumes that this means the command failed!  curl https://bootstrap.pypa.io/get-pip.py | sudo python

### ISSUE THREAD

**Issue by RalfEisler** [geerlingguy/drupal-vm#2146]
### Issue Type

 - Bug Report / Support Request

### Your Environment

 
```
Vagrant 2.2.7
VirtualBox 6.1.18r142142
```

### Your OS

 - **macOS** 10.14.6

### Full console output

https://gist.github.com/RalfEisler/9de98b2af48306a30cbce17bd62b7c31

### Summary

A fresh install of Drupal VM creates error:

```
Installing pip... (for Ansible installation)
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

curl https://bootstrap.pypa.io/get-pip.py | sudo python

Stdout from the command:

Stderr from the command:

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1884k  100 1884k    0     0  9238k      0 --:--:-- --:--:-- --:--:-- 9238k
Traceback (most recent call last):
  File "<stdin>", line 24244, in <module>
  File "<stdin>", line 199, in main
  File "<stdin>", line 82, in bootstrap
  File "/tmp/tmpRKuacm/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
```

**Comment by geerlingguy** [comment]
Thanks for the report! This is fixed by the fix referenced in https://github.com/geerlingguy/drupal-vm/issues/2138 (which is in master currently, but not in a release). Marking this as a duplicate, and I'll try to get out a release soon.
