### ISSUE TITLE
Error ensemble-galaxy El Capitan

### ISSUE THREAD

**Issue by ronsonmaria** [geerlingguy/drupal-vm#312]
Hello,

When I invoke the playbook i have this error:

ansimble version : 1.9.4

actually I get the same error even invoking ansible-playbook alone:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-galaxy", line 959, in <module>
    main()
  File "/usr/local/bin/ansible-galaxy", line 953, in main
    fn(args, options, parser)
  File "/usr/local/bin/ansible-galaxy", line 767, in execute_install
    roles_left = map(ansible.utils.role_yaml_parse, yaml.safe_load(f))
  File "/Library/Python/2.7/site-packages/ansible/utils/__init__.py", line 434, in role_yaml_parse
    if 'github.com' in role["src"] and 'http' in role["src"] and '+' not in role["src"] and not role["src"].endswith('.tar.gz'):
KeyError: 'src'

**Comment by geerlingguy** [comment]
It seems something's wrong with your Ansible installation. How did you install Ansible on your computer, and what's the output of `ansible --version`?

**Comment by geerlingguy** [comment]
I'm guessing this is due to an Ansible installation problem on your local machine. I'd try reinstalling using `brew` or `pip`.
