### ISSUE TITLE
Drupal console error in VM

### ISSUE THREAD

**Issue by mooru** [geerlingguy/drupal-vm#742]
I tried to download a module with drupal md but it throws this error even when i use sudo drupal console

PHP Fatal error:  Uncaught Error: Call to undefined function Drupal\Console\Command\drupal_static_reset() in phar:///usr/local/bin/drupal/src/Command/ProjectDownloadTrait.php:78
Stack trace:
#0 phar:///usr/local/bin/drupal/src/Command/Module/DownloadCommand.php(162): Drupal\Console\Command\Module\DownloadCommand->downloadModules(Object(Drupal\Console\Style\DrupalStyle), Array, false, 'modules/contrib')
#1 phar:///usr/local/bin/drupal/vendor/symfony/console/Command/Command.php(259): Drupal\Console\Command\Module\DownloadCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Drupal\Console\Style\DrupalStyle))
#2 phar:///usr/local/bin/drupal/vendor/symfony/console/Application.php(860): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Drupal\Console\Style\DrupalStyle))
#3 phar:///usr/local/bin/drupal/vendor/symfony/console/Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(Drupal\Console\Command\Module\DownloadCommand), Object in phar:///usr/local/bin/drupal/src/Command/ProjectDownloadTrait.php on line 78

Fatal error: Uncaught Error: Call to undefined function Drupal\Console\Command\drupal_static_reset() in phar:///usr/local/bin/drupal/src/Command/ProjectDownloadTrait.php:78
Stack trace:
#0 phar:///usr/local/bin/drupal/src/Command/Module/DownloadCommand.php(162): Drupal\Console\Command\Module\DownloadCommand->downloadModules(Object(Drupal\Console\Style\DrupalStyle), Array, false, 'modules/contrib')
#1 phar:///usr/local/bin/drupal/vendor/symfony/console/Command/Command.php(259): Drupal\Console\Command\Module\DownloadCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Drupal\Console\Style\DrupalStyle))
#2 phar:///usr/local/bin/drupal/vendor/symfony/console/Application.php(860): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Drupal\Console\Style\DrupalStyle))
#3 phar:///usr/local/bin/drupal/vendor/symfony/console/Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(Drupal\Console\Command\Module\DownloadCommand), Object in phar:///usr/local/bin/drupal/src/Command/ProjectDownloadTrait.php on line 78

**Comment by mooru** [comment]
Ok had to be in the web folder. my bad!!
