### ISSUE TITLE
Could not load config file /var/solr/collection1/solrconfig.xml

### ISSUE THREAD

**Issue by kevinquillen** [geerlingguy/drupal-vm#942]
After provisioning Solr and using the example script, I get this error when trying to access solr:

`Could not load config file /var/solr/collection1/solrconfig.xml`

Full error:

```
{msg=SolrCore 'collection1' is not available due to init failure: Could not load config file /var/solr/collection1/solrconfig.xml,trace=org.apache.solr.common.SolrException: SolrCore 'collection1' is not available due to init failure: Could not load config file /var/solr/collection1/solrconfig.xml
    at org.apache.solr.core.CoreContainer.getCore(CoreContainer.java:783)
    at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:295)
    at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:195)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.server.Server.handle(Server.java:368)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
    at org.eclipse.jetty.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:53)
    at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:942)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1004)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:640)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
    at org.eclipse.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:72)
    at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:264)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.solr.common.SolrException: Could not load config file /var/solr/collection1/solrconfig.xml
    at org.apache.solr.core.CoreContainer.createFromLocal(CoreContainer.java:490)
    at org.apache.solr.core.CoreContainer.create(CoreContainer.java:557)
    at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:247)
    at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:239)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    ... 1 more
Caused by: org.apache.solr.common.SolrException: Invalid luceneMatchVersion '5.0', valid values are: [LUCENE_30, LUCENE_31, LUCENE_32, LUCENE_33, LUCENE_34, LUCENE_35, LUCENE_36, LUCENE_40, LUCENE_41, LUCENE_42, LUCENE_43, LUCENE_44, LUCENE_45, LUCENE_CURRENT] or a string in format 'V.V'
    at org.apache.solr.core.Config.parseLuceneVersionString(Config.java:445)
    at org.apache.solr.core.Config.getLuceneVersion(Config.java:430)
    at org.apache.solr.core.SolrConfig.<init>(SolrConfig.java:131)
    at org.apache.solr.core.CoreContainer.createFromLocal(CoreContainer.java:487)
    ... 9 more
Caused by: java.lang.IllegalArgumentException: No enum constant org.apache.lucene.util.Version.LUCENE_50
    at java.lang.Enum.valueOf(Enum.java:236)
    at org.apache.lucene.util.Version.valueOf(Version.java:34)
    at org.apache.lucene.util.Version.parseLeniently(Version.java:152)
    at org.apache.solr.core.Config.parseLuceneVersionString(Config.java:443)
    ... 12 more
,code=500}
```

Any reason why it is looking at that path when the example script specifies SOLR_CORE_PATH as `/var/solr/data/collection1`?

**Comment by geerlingguy** [comment]
@kevinquillen - Did you modify the script at all (e.g. for Drupal 7 or something like that)? Also, what's the `solr_version` you're using? Different versions might set up the main core slightly differently...

**Comment by kevinquillen** [comment]
Nope, did not modify it.

I noticed that re-provisioning did nothing, so I ssh'd in and deleted the
file in /etc/ that it checks before running the script, ran it again. Same
result. Should be default solr version specified in Drupal VM 3.

**Comment by kevinquillen** [comment]
I just noticed I may have accidentally copied 5.x files while running Solr 4.x. Will report back.

**Comment by geerlingguy** [comment]
@kevinquillen - Closing this out for now... did it work?
